INSERT INTO `smf_stshop_categories` (`name`, `image`, `description`) VALUES
('Objetos - Generales', 'blank.gif', ''),
('Objetos - Armas Blancas', 'blank.gif', ''),
('Objetos - Criaturas', 'blank.gif', ''),
('Objetos - Estudiantes', 'blank.gif', ''),
('Objetos - EXTASIS', 'blank.gif', ''),
('Objetos - Hogwarts', 'blank.gif', ''),
('Objetos - Ingredientes de Rituales', 'blank.gif', ''),
('Objetos - Ministerio', 'blank.gif', ''),
('Objetos - Mortífagos', 'blank.gif', ''),
('Objetos - Pociones', 'blank.gif', ''),
('Objetos - Propiedades', 'blank.gif', ''),
('Objetos - Quidditch', 'blank.gif', ''),
('Objetos - Transporte Mágico', 'blank.gif', ''),
('Objetos - San Mungo', 'blank.gif', ''),
('Objetos - Autorizaciones', 'blank.gif', ''),
('Objetos - Premios Misiones', 'blank.gif', ''),
('Objetos - Premios Expediciones', 'blank.gif', ''),
('Objetos - Premios Nimbus', 'blank.gif', ''),
('Objetos - Premios Situaciones', 'blank.gif', ''),
('Objetos - Mini-tramas', 'blank.gif', ''),
('Objetos - San Duende', 'blank.gif', ''),
('Hechizos - Hechizos Básicos', 'blank.gif', ''),
('Hechizos - Hechizos de Sanación', 'blank.gif', ''),
('Hechizos - Hechizos de Ataque', 'blank.gif', ''),
('Hechizos - Hechizos de Defensa', 'blank.gif', ''),
('Hechizos - Hechizos de Ataque y Defensa', 'blank.gif', ''),
('Hechizos - Hechizos Aurores', 'blank.gif', ''),
('Hechizos - Hechizos Mortífagos', 'blank.gif', ''),
('Hechizos - Maleficios', 'blank.gif', ''),
('Razas - Razas', 'blank.gif', ''),
('Habilidades - Habilidades Innatas', 'blank.gif', ''),
('Habilidades - Habilidades Adquiribles', 'blank.gif', ''),
('Habilidades - Habilidades de Licántropos', 'blank.gif', ''),
('Habilidades - Habilidades de Semigigantes', 'blank.gif', ''),
('Habilidades - Habilidades Sirenas', 'blank.gif', ''),
('Habilidades - Habilidades de Vampiros', 'blank.gif', ''),
('Habilidades - Habilidades de Veela', 'blank.gif', ''),
('Habilidades - Habilidades de Híbridos Innatas', 'blank.gif', ''),
('Habilidades - Habilidades de Humanos', 'blank.gif', ''),
('Costello - Arcana High Bar', 'blank.gif', ''),
('Costello - Borgin & Burkes', 'blank.gif', ''),
('Costello - El Nox', 'blank.gif', ''),
('Costello - Mortem Gemma', 'blank.gif', ''),
('Costello - Portafolio', 'blank.gif', ''),
('Negocios - Aquí te tengo tu cariñito', 'blank.gif', ''),
('Negocios - Báthory Square Garden', 'blank.gif', ''),
('Negocios - Botica Slug & Jiggers', 'blank.gif', ''),
('Negocios - Chez Winnie', 'blank.gif', ''),
('Negocios - Danceteria Rolling Hall', 'blank.gif', ''),
('Negocios - El Lux', 'blank.gif', ''),
('Negocios - FLEUR', 'blank.gif', ''),
('Negocios - Flourish & Blotts', 'blank.gif', ''),
('Negocios - Luxxuria', 'blank.gif', ''),
('Negocios - Moonlight Shadow Planetary', 'blank.gif', ''),
('Negocios - Mystic Momentum', 'blank.gif', ''),
('Negocios - Nym\'s Treasure', 'blank.gif', ''),
('Negocios - Peonie\'s Ribbon', 'blank.gif', ''),
('Negocios - Plants & Seeds', 'blank.gif', ''),
('Negocios - Ragnarok', 'blank.gif', ''),
('Negocios - Rose', 'blank.gif', ''),
('Negocios - Royal Vauxhall Tavern', 'blank.gif', ''),
('Negocios - Sacred Lotus', 'blank.gif', ''),
('Negocios - Saint Ellis Hospital', 'blank.gif', ''),
('Negocios - Sortilegios Weasley', 'blank.gif', ''),
('Negocios - Tierra y Cristal', 'blank.gif', ''),
('Negocios - Vinos Zabini', 'blank.gif', ''),
('Negocios - Wizarding World Curse', 'blank.gif', ''),
('Logros - Logros de Colaborador del Mes', 'blank.gif', ''),
('Logros - Logros de Personaje del Mes', 'blank.gif', ''),
('Logros - Logros de Awards', 'blank.gif', ''),
('Logros - Logros de Duelos', 'blank.gif', ''),
('Logros - Logros de Misiones', 'blank.gif', ''),
('Logros - Logros de Misiones', 'blank.gif', ''),
('Logros - Logros de Expediciones', 'blank.gif', ''),
('Logros - Logros de Pociones', 'blank.gif', ''),
('Logros - Logros de Nimbus', 'blank.gif', ''),
('Logros - Logros de Situaciones', 'blank.gif', ''),
('Logros - Logros de Cámara de Creación Mágica', 'blank.gif', ''),
('Logros - Logros de Rituales', 'blank.gif', ''),
('Logros - Logros de San Mungo', 'blank.gif', ''),
('Logros - Logros de Costello', 'blank.gif', ''),
('Logros - Logros de Colección de Cromos', 'blank.gif', ''),
('Logros - Logros de Top Posteadores', 'blank.gif', ''),
('Logros - Logros de Empleo', 'blank.gif', ''),
('Logros - Logros de Hall of Fame', 'blank.gif', ''),
('Logros - Logros de Torneo de Duelos', 'blank.gif', ''),
('Logros - Logros de Torneo de Pociones', 'blank.gif', ''),
('Logros - Logros de Torneo de Quidditch Libre', 'blank.gif', ''),
('Logros - Logros de Desafío Hogwarts', 'blank.gif', ''),
('Logros - Logros de Mortífagos', 'blank.gif', ''),
('Logros - Logros de Aurores', 'blank.gif', '');