INSERT INTO `smf_stshop_categories` (`name`, `image`, `description`) VALUES
    ('Costello - Arcana High Bar', 'blank.gif', ''),
    ('Costello - Borgin & Burkes', 'blank.gif', ''),
    ('Costello - El Nox', 'blank.gif', ''),
    ('Costello - Mortem Gemma', 'blank.gif', ''),
    ('Costello - Portafolio', 'blank.gif', ''),
    ('Negocios - Bathory Square Garden', 'blank.gif', ''),
    ('Negocios - Botica Slug & Jiggers', 'blank.gif', ''),
    ('Negocios - Chez Winnie', 'blank.gif', ''),
    ('Negocios - El Lux', 'blank.gif', ''),
    ('Negocios - FLEUR', 'blank.gif', ''),
    ('Negocios - Flourish & Blotts', 'blank.gif', ''),
    ('Negocios - Luxxuria', 'blank.gif', ''),
    ('Negocios - Moonlight Shadow Planet', 'blank.gif', ''),
    ('Negocios - Nym\'s Treasure', 'blank.gif', ''),
    ('Negocios - Peonie\'s Ribbon', 'blank.gif', ''),
    ('Negocios - Plants & Seeds', 'blank.gif', ''),
    ('Negocios - Ragnarok', 'blank.gif', ''),
    ('Negocios - Rose', 'blank.gif', ''),
    ('Negocios - Sacred Lotus', 'blank.gif', ''),
    ('Negocios - Saint Ellis Hospital', 'blank.gif', ''),
    ('Negocios - Sortilegios Weasley', 'blank.gif', ''),
    ('Negocios - Tierra y Cristal', 'blank.gif', ''),
    ('Negocios - Vinos Zabini', 'blank.gif', ''),
    ('Negocios - Wizarding World Curse', 'blank.gif', ''),
    ('Hechizos - Neutrales', 'blank.gif', ''),
    ('Hechizos - Ofensivos', 'blank.gif', ''),
    ('Hechizos - Sanación', 'blank.gif', ''),
    ('Hechizos - Maleficios', 'blank.gif', ''),
    ('Habilidades - Especiales', 'blank.gif', ''),
    ('Habilidades - Licántropos', 'blank.gif', ''),
    ('Habilidades - Semigigantes', 'blank.gif', ''),
    ('Habilidades - Sirenas', 'blank.gif', ''),
    ('Habilidades - Vampiros', 'blank.gif', ''),
    ('Habilidades - Veelas', 'blank.gif', ''),
    ('Objetos - Generales', 'blank.gif', ''),
    ('Objetos - Armas Blancas', 'blank.gif', ''),
    ('Objetos - Criaturas', 'blank.gif', ''),
    ('Objetos - Estudiantes', 'blank.gif', ''),
    ('Objetos - Hogwarts', 'blank.gif', ''),
    ('Objetos - Ingredientes', 'blank.gif', ''),
    ('Objetos - Ministerio', 'blank.gif', ''),
    ('Objetos - Mortífagos', 'blank.gif', ''),
    ('Objetos - Pociones', 'blank.gif', ''),
    ('Objetos - Propiedades', 'blank.gif', ''),
    ('Objetos - Quidditch', 'blank.gif', ''),
    ('Objetos - San Mungo', 'blank.gif', ''),
    ('Objetos - Transporte Mágico', 'blank.gif', '');